/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * EV Match Singapore API
 * OpenAPI spec version: 0.1.0
 */
import { z } from "zod";

// ─── Health ───────────────────────────────────────────────────────────────────

/**
 * Returns server health status
 * @summary Health check
 */
export const HealthCheckResponse = z.object({
  status: z.string(),
});
export type HealthCheckResponse = z.infer<typeof HealthCheckResponse>;

// ─── Cars ─────────────────────────────────────────────────────────────────────

/**
 * Returns all available EV models in Singapore
 * @summary List all EV models
 */
export const GetCarsResponseItem = z.object({
  id: z.string(),
  name: z.string(),
  brand: z.string(),
  model: z.string(),
  priceMin: z.number(),
  priceMax: z.number(),
  rangeKm: z.number(),
  carType: z.enum(["Sedan", "SUV", "Hatchback", "MPV"]),
  chargingTimeFast: z.string(),
  chargingTimeSlow: z.string(),
  rebateEligible: z.boolean(),
  rebateAmount: z.number().nullish(),
  acceleration: z.string(),
  topSpeed: z.number(),
  seats: z.number(),
  imageUrl: z.string(),
  highlights: z.array(z.string()),
  monthlyEstimate: z.number(),
  description: z.string(),
});
export type GetCarsResponseItem = z.infer<typeof GetCarsResponseItem>;

export const GetCarsResponse = z.array(GetCarsResponseItem);
export type GetCarsResponse = z.infer<typeof GetCarsResponse>;

/**
 * Returns details for one EV model by slug id
 * @summary Get a single EV model
 */
export const GetCarParams = z.object({
  id: z.coerce.string(),
});
export type GetCarParams = z.infer<typeof GetCarParams>;

export const GetCarResponse = z.object({
  id: z.string(),
  name: z.string(),
  brand: z.string(),
  model: z.string(),
  priceMin: z.number(),
  priceMax: z.number(),
  rangeKm: z.number(),
  carType: z.enum(["Sedan", "SUV", "Hatchback", "MPV"]),
  chargingTimeFast: z.string(),
  chargingTimeSlow: z.string(),
  rebateEligible: z.boolean(),
  rebateAmount: z.number().nullish(),
  acceleration: z.string(),
  topSpeed: z.number(),
  seats: z.number(),
  imageUrl: z.string(),
  highlights: z.array(z.string()),
  monthlyEstimate: z.number(),
  description: z.string(),
});
export type GetCarResponse = z.infer<typeof GetCarResponse>;

// ─── Recommendation ───────────────────────────────────────────────────────────

/**
 * Send quiz answers and receive top 3 personalised EV recommendations
 * @summary Get AI EV recommendation
 */
export const GetRecommendationBody = z.object({
  budget: z.enum(["under150k", "150k-200k", "200k-250k", "above250k"]),
  dailyDistanceKm: z.enum(["under50", "50-100", "100-150", "above150"]),
  hasHomeCharging: z.boolean(),
  carType: z.enum(["sedan", "suv", "any"]),
  priority: z.enum(["saveMoney", "performance", "techFeatures", "range"]),
});
export type GetRecommendationBody = z.infer<typeof GetRecommendationBody>;

export const RecommendationItem = z.object({
  carId: z.string(),
  carName: z.string(),
  rank: z.number(),
  reasoning: z.string(),
  monthlyEstimate: z.number(),
  chargingStrategy: z.string(),
  fitScore: z.number(),
});
export type RecommendationItem = z.infer<typeof RecommendationItem>;

export const GetRecommendationResponse = z.object({
  recommendations: z.array(RecommendationItem),
  summary: z.string(),
});
export type GetRecommendationResponse = z.infer<
  typeof GetRecommendationResponse
>;

// ─── Leads ────────────────────────────────────────────────────────────────────

/**
 * Capture a qualified EV buyer lead
 * @summary Submit a lead
 */
export const CreateLeadBody = z.object({
  name: z.string(),
  phone: z.string(),
  email: z.string(),
  preferredCar: z.string(),
  quizAnswers: z.string().nullish(),
  recommendationResult: z.string().nullish(),
});
export type CreateLeadBody = z.infer<typeof CreateLeadBody>;

/**
 * Returns all captured leads for admin/dealer view
 * @summary List all leads (admin)
 */
export const GetLeadsResponseItem = z.object({
  id: z.number(),
  name: z.string(),
  phone: z.string(),
  email: z.string(),
  preferredCar: z.string(),
  quizAnswers: z.string().nullish(),
  recommendationResult: z.string().nullish(),
  createdAt: z.coerce.date(),
});
export type GetLeadsResponseItem = z.infer<typeof GetLeadsResponseItem>;

export const GetLeadsResponse = z.array(GetLeadsResponseItem);
export type GetLeadsResponse = z.infer<typeof GetLeadsResponse>;

/**
 * Returns total count and breakdown by preferred car
 * @summary Get lead statistics
 */
export const GetLeadStatsResponse = z.object({
  total: z.number(),
  byPreferredCar: z.array(
    z.object({
      car: z.string(),
      count: z.number(),
    }),
  ),
  recentLeads: z.array(GetLeadsResponseItem),
});
export type GetLeadStatsResponse = z.infer<typeof GetLeadStatsResponse>;
